---
# See https://pre-commit.com/#new-hooks
# reliabot: mapping=2 offset=0 sequence=2 width=77
- id: reliabot
  name: Maintain dependabot configuration
  description: Searches repo for package ecosystems and updates dependabot.
  entry: reliabot
  args: [--update]
  pass_filenames: false
  language: python
  additional_dependencies:
    # https://github.com/dupuy/reliabot/blob/main/README.md#installing-with-re2
    # Add this to additional_dependencies in your .pre-commit-config.yaml to get
    # RE2 support (requires C++ RE2 library, `brew install re` or similar).
    # - pyre2-updated
    - ruamel.yaml
  stages: [manual, pre-commit, pre-merge-commit, pre-push]
  exclude_types: [binary, directory, symlink]
  # prettier-ignore
  files: >-
    (?x)(^|/)(
      gem(s[.]rb|file)|[\w.-]*[.]gemspec|
      cargo[.]toml|
      composer[.]json|
      (?i:[\w.-]*dockerfile[\w.-]*|values[\w.-]*[.]ya?ml)|
      elm(-package)?[.]json|
      action[.]yml|
      [.]gitmodules|
      go[.]mod|
      build[.]gradle([.]kts)?|
      mix[.]exs|
      pom[.]xml|
      package[.]json|
      nuget[.]config|
      requirements[.]txt|pyproject[.]toml|
      pubspec[.]yaml|
      \w[\w.-]*[.](?:hcl|tf)|
      [.]github/workflows/[^/]*[.]ya?ml|
      [.]github/dependabot[.]yml
      )$
