# Source repository: https://github.com/codacy/codacy-coverage-reporter-action/blob/master/README.md#uploading-coverage-to-codacy

name: 'Codacy Coverage Reporter'
on:
  workflow_run:
    workflows: ['Run tests with coverage']
    types:
      - completed

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-24.04
    name: codacy-coverage-reporter
    permissions:
      contents: read
      actions: read # Needed to download artifacts
    # Only run on primary fork, since this requires a Codacy project token
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.repository == 'dupuy/reliabot'
    steps:
      - name: 'Harden runner'
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            api.codacy.com:443
            api.github.com:443
            artifacts.codacy.com:443
            github.com:443
            objects.githubusercontent.com:443

      - name: 'Download coverage report'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run download ${{ github.event.workflow_run.id }} --name coverage-report

      - name: 'Run codacy-coverage-reporter'
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          language: Python
          coverage-reports: 'cobertura.xml'
