# .github/workflows/publish.yml
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/reliabot
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
    steps:
      # retrieve your distributions here

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf # 1.8.11

        https://github:com/pypa/gh-action-pypi-publish/commit/:
