# This workflow runs for pull requests and pushes (merge/squash/rebase or tags).

# The TESTS job always runs, installing Python Poetry dependencies, building a
# distribution and running tests on a matrix of Python versions. It also
# computes several outputs for use by other jobs, often in 'if' conditions.
#
# The first output (VERSION_TAG) describes the intended Reliabot version, which
# can be the current tag, but is usually a desired (pre-)release tag for this
# workflow to apply, or the "left over" version of the most recent release tag.
# All outputs are set as environment variables in the jobs that use them, but
# this one uses underscore '_' rather than hyphen '-' in its name so that shell
#'run' scripts can use it as an environment variable rather than as a '${{ }}'
# substitution that would be vulnerable to shell meta-characters in the value.
# Although TESTS uses `poetry version` to get this value from 'pyproject.toml',
# and poetry rejects metacharacters in the version, it's still worth having
# m shell-compatible name to protect against a compromised action or workflow
# exploiting this environment variable by overriding the poetry-computed value.
#
# The TESTS job uses `git describe` to compute another variable (COMMIT_TAG)
# that is not an output. Its value can be the current VERSION_TAG ("v1.2.3") or
# a previous VERSION_TAG followed by '-', the number of further commits, and
# a short commit hash, like this: 'v1.2.3-13-ca11ab1e'. The latter indicates an
# "interim" (untagged) commit, and can be distinguished from a pre-release tag
# like `v1.2.3-rc.5' by the presence of a second '-'.
#
# The TESTS job uses these two variables to determine the type of push (merge)
# or pull request the workflow is handling, and creates "pr-*" outputs for other
# jobs to use in 'if' conditions to enable execution of various job steps.
#
# * pr-commit  :: COMMIT_TAG != VERSION_TAG
# * pr-release :: VERSION_TAG has no '-'
# * pr-tag     :: COMMIT_TAG does not start with VERSION_TAG + '-'
#
# [The pr-tag test uses '-' to prevent 'v1.2.10' starts with 'v1.2.1' mistakes.]
#
# - Tag push:     pr-commit=false pr-release=false pr-tag=false (take no action)
# - "Interim" PR: pr-commit=true pr-release=false pr-tag=false (no tag/release)
# - Pre-release:  pr-commit=true pr-release=false pr-tag=true (tag + TestPyPI)
# - Release:      pr-commit=true pr-release=true pr-tag=true (annotated + PyPI)
#
# [Only releases use annotated tags so `git describe` ignores pre-releases.]
# [Also note pr-tag=true implies pr-commit=true so latter test may be omitted.]
#
# The TESTS job also computes two other outputs to coordinate (upload/download)
# between the pull_request and push workflows, and the jobs within them:
#
# - artifact-name - GitHub artifact containing dist/ release for publishing
# - release-name - GitHub title of release or pre-release

# Since only the last matrix instance output is available, and there's no way to
# know which one that is, all matrix instances compute the outputs.
#
# All other jobs run only on one or the other of pull_request or push events:
#
# pull_request:  build → draft-release, test-publish
# push:          pre-release || ( publish → release )

# The BUILD job creates a Python package release, release notes, and a full
# changelog, uploading them as artifacts for other pull_request and push jobs.
# The lifetime of these artifacts is linked to the "stale" workflow that closes
# inactive PRs. By closing PRs before their artifacts expire, the stale workflow
# prevents push workflow failures. The pull_request workflow runs on "reopen"
# or "ready for review" events, recreating expired artifacts before any "push".

name: 'Test, build, release, and upload Python Poetry app'

env:
  OUTPUT: dist/release-notes.md # from release.toml
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-24.04

    outputs:
      VERSION_TAG: ${{ steps.computed.outputs.VERSION_TAG }}
      artifact-name: ${{ steps.computed.outputs.artifact-name }}
      pr-commit: ${{ steps.computed.outputs.pr-commit }}
      pr-release: ${{ steps.computed.outputs.pr-release }}
      pr-tag: ${{ steps.computed.outputs.pr-tag }}
      release-name: ${{ steps.computed.outputs.release-name }}
    strategy:
      matrix:
        fail-fast: [false] # while trying to understand failure causes
        max-concurrency: [5]
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'

    steps:
      - name: 'Harden runner'
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      - name: 'Checkout repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # The `git describe` COMMIT_TAG output requires these fetch-* options.
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: 'Install Poetry'
        run: 'pipx install poetry'

      - name: 'Compute outputs for other jobs'
        id: computed
        run: >
          {
            COMMIT_TAG=$(git describe) &&
              echo "COMMIT_TAG=$COMMIT_TAG" >&2 ;
            VERSION_TAG="v`poetry version --short |
              sed -e 's/a/-alpha./' -e 's/b/-beta./' -e 's/rc/-rc./'`" &&
                echo "VERSION_TAG=$VERSION_TAG" ;
            case "$COMMIT_TAG" in
              *-[abr]*-[1-9]*-*)
                exec >&2
                echo "The COMMIT_TAG that 'git describe' created is based on" ;
                echo "a pre-release tag, which prevents proper generation" ;
                echo "of new releases!" ;
                echo "Make sure git describe is not using --tags, and use" ;
                echo "'git show' to check if the pre-release base tag is" ;
                echo "an annotated tag like release tags."
                exit 1 ;;
              ${VERSION_TAG})
                echo "artifact-name=" ;
                echo "pr-commit=false" ; echo "pr-tag=false" ;
                echo "pr-release=false" ; echo "release-name=" ;;
              ${VERSION_TAG}-*)
                echo "artifact-name=" ;
                echo "pr-commit=true" ; echo "pr-tag=false" ;
                echo "pr-release=false" ; echo "release-name=" ;;
              *)
                echo "artifact-name=dist-reliabot-$VERSION_TAG" ;
                echo "pr-commit=true" ; echo "pr-tag=true" ;
                case "$VERSION_TAG" in
                  *-*)
                    echo "pr-release=false" ;
                    echo "release-name=Pre-release $VERSION_TAG" ;;
                  *)
                    echo "pr-release=true" ;
                    echo "release-name=Release $VERSION_TAG" ;;
                esac ;
            esac ;
          } | tee -a "$GITHUB_OUTPUT"

      - name: 'Set up Python'
        if: steps.computed.outputs.pr-commit == 'true'
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '${{ matrix.python-version }}'
          cache: 'poetry'

      - name: 'Install dependencies with extras'
        if: >
          steps.computed.outputs.pr-commit == 'true' &&
          matrix.python-version != 3.13 && matrix.python-version != 3.14
        run: 'poetry install --extras re2-wheels --with testing'

      - name: 'Install dependencies without extras'
        if: >
          steps.computed.outputs.pr-commit == 'true' &&
          (matrix.python-version == 3.13 || matrix.python-version == 3.14)
        run: 'poetry install --with testing'

      - name: 'Run tests with coverage'
        if: steps.computed.outputs.pr-commit == 'true'
        run: 'poetry run tox -e py'

  build:
    runs-on: ubuntu-24.04

    # Build for pull requests AND for release-related push events to main.
    if: >
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && needs.tests.outputs.pr-tag == 'true')
    env:
      VERSION_TAG: ${{ needs.tests.outputs.VERSION_TAG }}
      artifact-name: ${{ needs.tests.outputs.artifact-name }}
      pr-commit: ${{ needs.tests.outputs.pr-commit }}
      pr-release: ${{ needs.tests.outputs.pr-release }}
      pr-tag: ${{ needs.tests.outputs.pr-tag }}
      release-name: ${{ needs.tests.outputs.release-name }}
    needs:
      - tests
    permissions:
      id-token: write # IMPORTANT: trusted signing requires this permission
      contents: read

    steps:
      - name: 'Harden runner'
        if: env.pr-commit == 'true'
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            files.pythonhosted.org:443
            fulcio.sigstore.dev:443
            github.com:443
            oauth2.sigstore.dev:443
            objects.githubusercontent.com:443
            pypi.org:443
            rekor.sigstore.dev:443
            release-assets.githubusercontent.com:443
            sigstore-tuf-root.storage.googleapis.com:443

      - name: 'Checkout repository'
        if: env.pr-commit == 'true'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # The `git-cliff` release notes action requires these fetch-* options.
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: 'Install Poetry'
        if: env.pr-commit == 'true'
        run: 'pipx install poetry'

      - name: 'Set up Python'
        if: env.pr-commit == 'true'
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '>=3.9 <3.15'
          cache: 'poetry'

      - name: 'Build distribution packages'
        if: env.pr-commit == 'true'
        run: 'poetry build'

      - name: 'Sign built artifacts'
        if: env.pr-commit == 'true'
        uses: sigstore/gh-action-sigstore-python@f514d4670c5765796c8105741630c79e657c9636 # v3.0.0
        with:
          inputs: >
            dist/*.tar.gz
            dist/*.whl

      - name: 'Generate release notes'
        if: env.pr-tag == 'true'
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5 # v4.8.0
        with:
          args: >
            '--unreleased'
            '--tag=${{ env.VERSION_TAG }}'
          config: release.toml
          version: 'v2.9.1'

      - name: 'Generate "unreleased" notes'
        if: env.pr-commit == 'true' && env.pr-tag == 'false'
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5 # v4.8.0
        with:
          args: '--unreleased'
          config: release.toml
          version: 'v2.9.1'

      - name: 'Generate metadata for privileged tasks'
        if: env.pr-tag == 'true'
        run: |
          cat <<EOF > dist/metadata.json
          {
            "VERSION_TAG": "${{ env.VERSION_TAG }}",
            "artifact-name": "${{ env.artifact-name }}",
            "pr-release": "${{ env.pr-release }}",
            "pr-tag": "${{ env.pr-tag }}",
            "release-name": "${{ env.release-name }}"
          }
          EOF

      - name: 'Upload distribution package as an artifact'
        if: github.repository == 'dupuy/reliabot' && env.pr-tag == 'true'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          if-no-files-found: error
          name: '${{ env.artifact-name }}'
          overwrite: true
          path: 'dist/*'
          retention-days: 90 # stale + close + 13 <= artifact retention (90 max)
