# .github/workflows/stale.yml
# This workflow warns and then closes issues and PRs with no recent activity.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '23 11 * * 1-5'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v9
        with:
          exempt-all-pr-assignees: true
          stale-issue-label: 'inactive-issue'
          stale-issue-message: 'This will be closed if there’s no activity soon'
          stale-pr-label: 'inactive-pr'
          stale-pr-message: 'This PR will be closed if there’s no activity soon'
